version: '3'
services: 
  api: 
    restart: always
    build: ../../.
    expose:
      - 3000
    ports:
      - 3000:3000
    networks:
     - web
    environment: 
      - dockerNetwork=web
      - gqlProxyToken=1234
      - qglProxyRuntime=docker
      - gqlProxyKnownOldSchemas=true
    volumes: 
     - /var/run/docker.sock:/var/run/docker.sock
networks:
  web:
    external: true