pipeline: 
  test: 
    image: alpine
    commands: 
      - env
  build: 
   iamge: plugins/docker
   secrets: [ docker_username, docker_password ]    
   repo: fasibio/graphqldockerproxy
   tags: [rc_0.0.9]
    
