build:
  stage: build
  tags: 
    - dockerfasibio
  image: docker
  script:
    - ls -lag
    - sh -x ./dockerize/buildDocker.sh latest
  only:
    - master
publish:
  stage: publish
  tags: 
    - dockerfasibio
  image: docker
  script:
    - sh -x ./dockerize/publish.sh latest
  only:
    - master
stages: 
  - build
  - publish