  build:
    stage: build
    tags: 
      - dockerfasibio
    image: docker
    script:
      - sh -x ./dockerize/buildDocker.sh latest
    only:
      - master
      - /^rc_([0-9]{0,3})\.([0-9]{0,3})\.([0-9]{0,3})$/
  publish:
    stage: publish
    tags: 
      - dockerfasibio
    image: docker
    script:
      - sh -x ./dockerize/publish.sh latest
    only:
      - master
      - /^rc_([0-9]{0,3})\.([0-9]{0,3})\.([0-9]{0,3})$/
  buildTag:
    stage: build
    tags: 
      - dockerfasibio
    image: docker
    script:
      - sh -x ./dockerize/buildDocker.sh $CI_COMMIT_TAG
    only:
      - /^([0-9]{0,3})\.([0-9]{0,3})\.([0-9]{0,3})$/
      - /^rc_([0-9]{0,3})\.([0-9]{0,3})\.([0-9]{0,3})$/
    except:
      - tags
    
  publishTag:
    stage: publish
    tags: 
      - dockerfasibio
    image: docker
    script:
      - sh -x ./dockerize/publish.sh $CI_COMMIT_TAG
    only:
      - /^([0-9]{0,3})\.([0-9]{0,3})\.([0-9]{0,3})$/
      - /^rc_([0-9]{0,3})\.([0-9]{0,3})\.([0-9]{0,3})$/
    except:
      - tags
  stages: 
    - build
    - publish