  test:
    stage: test
    tags:
      - dockerfasibio
    image: node:9
    script:
      - npm install
      - npm test -- --coverage=true
    coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
    artifacts:
      paths:
        - coverage/
        - reports/
    only:
      - /^([0-9]{0,3})\.([0-9]{0,3})\.([0-9]{0,3})$/
      - /^rc_([0-9]{0,3})\.([0-9]{0,3})\.([0-9]{0,3})$/
      - master

  sonarqubeAnalyse:
    stage: sonar
    tags:
      - dockerfasibio
    image: ciricihq/gitlab-sonar-scanner
    artifacts:
      paths:
        - coverage/
        - reports/
    script:
      - ls -al
      - cp coverage/clover.xml .
      - sh -x ./sonarexec.sh
    only:
      - /^([0-9]{0,3})\.([0-9]{0,3})\.([0-9]{0,3})$/
      - /^rc_([0-9]{0,3})\.([0-9]{0,3})\.([0-9]{0,3})$/
      - master

  pages:
    stage: testPages
    tags:
        - dockerfasibio
    dependencies:
      - test
    script:
      - mv coverage/lcov-report public/
    artifacts:
      paths:
        - public
      expire_in: 30 days
    only:
      - master
  build:
    stage: build
    tags: 
      - dockerfasibio
    image: docker
    script:
      - sh -x ./dockerize/buildDocker.sh latest
    only:
      - master

  # integrationTest:
  #   stage: integrationtest
  #   tags: 
  #     - dockerfasibio
  #   image: node:9
  #   services:
  #     - fasibio/graphqldockerproxy:$CI_COMMIT_REF_NAME
  #   only:
  #     - /^([0-9]{0,3})\.([0-9]{0,3})\.([0-9]{0,3})$/
  #     - /^rc_([0-9]{0,3})\.([0-9]{0,3})\.([0-9]{0,3})$/
  #   script:
  #     - env
  #     - ls /var/run/
  

  publish:
    stage: publish
    tags: 
      - dockerfasibio
    image: docker
    script:
      - sh -x ./dockerize/publish.sh latest
    only:
      - master
  buildTag:
    stage: build
    tags: 
      - dockerfasibio
    image: docker
    script:
      - sh -x ./dockerize/buildDocker.sh $CI_COMMIT_REF_NAME
    only:
      - /^([0-9]{0,3})\.([0-9]{0,3})\.([0-9]{0,3})$/
      - /^rc_([0-9]{0,3})\.([0-9]{0,3})\.([0-9]{0,3})$/

    
  publishTag:
    stage: publish
    tags: 
      - dockerfasibio
    image: docker
    script:
      - sh -x ./dockerize/publish.sh $CI_COMMIT_REF_NAME
    only:
      - /^([0-9]{0,3})\.([0-9]{0,3})\.([0-9]{0,3})$/
      - /^rc_([0-9]{0,3})\.([0-9]{0,3})\.([0-9]{0,3})$/
  
  cleanup:
    stage: cleanup
    tags: 
      - dockerfasibio
    image: docker
    script:
      - docker rmi fasibio/graphqldockerproxy:$CI_COMMIT_REF_NAME
    only:
      - /^([0-9]{0,3})\.([0-9]{0,3})\.([0-9]{0,3})$/
      - /^rc_([0-9]{0,3})\.([0-9]{0,3})\.([0-9]{0,3})$/
     
  cleanupLatest: 
    stage: cleanup
    tags: 
      - dockerfasibio
    image: docker
    script:
      - docker rmi fasibio/graphqldockerproxy:latest
    only:
      - master
  stages: 
    - test
    - testPages
    - sonar
    - build
    # - integrationtest
    - publish
    - cleanup